export const termsAndConditions = [
  "The competition is open to all Indian Citizens.",
  "The Essay should be either in English or Assamese. ",
  "Word limit of the Essay should not be more than 1000 words.",
  "Last date and time of submission of essays is 5 PM of 25th September 2020.",
  "Results will be declared on 30th September 2020.",
  "The decision of the Selection Committee of Assam Police Headquarters shall be final.",
  "The Essays may be uploaded on https://assampoliceday.org.",
  "Participants need to submit their details like Full Name, Address, Phone Number, Email ID etc on the above-mentioned link.",
  "Participants must submit an undertaking stating that Essay submitted by him/her is original and should not violate any provision of the Indian Copyright Act, 1957 by clicking on the declaration present on the above link.",
  "Essays should be uploaded in .pdf format only.",
  "Each competitor may submit only one essay, either in English or in Assamese.",
  "Essay must reflect the original thinking and creativity of the participant.",
  "Essays should not contain statements, facts, information, or quotations that may harm any person or group of persons or institutions.",
  "Assam Police Headquarters reserves the right to cancel/amend all or any part of the contest or any entry which does not comply by the given rules.",
  "For any clarifications regarding the rules and procedures, kindly mail on aigp.logistics@assampolice.gov.in.",
];
